### ISSUE TITLE
dll 加载报错 OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by summerwbb** [smartkids77/ArcSoft_FreeSDK_Demo#7]
C:\Users\wbb\AppData\Local\Programs\Python\Python36\python.exe "F:/face/ARC/06080/python - 副本/web.py"
Traceback (most recent call last):
  File "F:/face/ARC/06080/python - 副本/web.py", line 5, in <module>
    from arcsoft.AFD_FSDKLibrary import *
  File "F:\face\ARC\06080\python - 副本\arcsoft\AFD_FSDKLibrary.py", line 35, in <module>
    internalLibrary =  CDLL(u'face_detection.dll')
  File "C:\Users\wbb\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

请问怎么解决啊 找了很久都解决不了 在其他人的电脑上没有问题

**Comment by qiongqiongz** [comment]
你好，请问解决了吗，我也遇到这种问题，在其他人的电脑上没有问题

**Comment by jcluo1994** [comment]
> C:\Users\wbb\AppData\Local\Programs\Python\Python36\python.exe "F:/face/ARC/06080/python - 副本/web.py" Traceback (most recent call last): File "F:/face/ARC/06080/python - 副本/web.py", line 5, in from arcsoft.AFD_FSDKLibrary import * File "F:\face\ARC\06080\python - 副本\arcsoft\AFD_FSDKLibrary.py", line 35, in internalLibrary = CDLL(u'face_detection.dll') File "C:\Users\wbb\AppData\Local\Programs\Python\Python36\lib\ctypes__init__.py", line 348, in **init** self._handle = _dlopen(self._name, mode) OSError: [WinError 126] 找不到指定的模块。
> 
> 请问怎么解决啊 找了很久都解决不了 在其他人的电脑上没有问题

你是不是用的win10 lstc版本的系统？

**Comment by kivenyangming** [comment]
请问您的dll,是用C++生成的么？如果是的话可以将VS配置中的代码生成MDd更换为MTd。我的是这样解决的。
